# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'applicationwindow_view.ui'
#
# Created: Thu Apr 26 11:37:09 2012
#      by: PyQt4 UI code generator 4.8.5
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_ApplicationWindow(object):
    def setupUi(self, ApplicationWindow):
        ApplicationWindow.setObjectName(_fromUtf8("ApplicationWindow"))
        ApplicationWindow.resize(1024, 768)
        font = QtGui.QFont()
        font.setPointSize(10)
        ApplicationWindow.setFont(font)
        ApplicationWindow.setWindowTitle(QtGui.QApplication.translate("ApplicationWindow", "EMC Testbench", None, QtGui.QApplication.UnicodeUTF8))
        ApplicationWindow.setDockNestingEnabled(True)
        self.centralwidget = QtGui.QWidget(ApplicationWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setMargin(0)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.mainTabWidget = QtGui.QTabWidget(self.centralwidget)
        self.mainTabWidget.setTabPosition(QtGui.QTabWidget.South)
        self.mainTabWidget.setObjectName(_fromUtf8("mainTabWidget"))
        self.resultsTab = QtGui.QWidget()
        self.resultsTab.setObjectName(_fromUtf8("resultsTab"))
        self.horizontalLayout_5 = QtGui.QHBoxLayout(self.resultsTab)
        self.horizontalLayout_5.setContentsMargins(3, 3, 3, 6)
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.experimentResultTree = ExperimentResultCollectionController(self.resultsTab)
        self.experimentResultTree.setObjectName(_fromUtf8("experimentResultTree"))
        self.horizontalLayout_5.addWidget(self.experimentResultTree)
        self.mainTabWidget.addTab(self.resultsTab, _fromUtf8(""))
        self.experimentTab = QtGui.QWidget()
        self.experimentTab.setObjectName(_fromUtf8("experimentTab"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.experimentTab)
        self.horizontalLayout_2.setMargin(3)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.experimentTree = ExperimentTreeWidget(self.experimentTab)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("MS Shell Dlg 2"))
        font.setPointSize(10)
        self.experimentTree.setFont(font)
        self.experimentTree.setContextMenuPolicy(QtCore.Qt.CustomContextMenu)
        self.experimentTree.setIconSize(QtCore.QSize(18, 18))
        self.experimentTree.setColumnCount(1)
        self.experimentTree.setObjectName(_fromUtf8("experimentTree"))
        self.experimentTree.headerItem().setText(0, _fromUtf8("1"))
        self.experimentTree.header().setVisible(False)
        self.experimentTree.header().setMinimumSectionSize(1)
        self.horizontalLayout_2.addWidget(self.experimentTree)
        self.mainTabWidget.addTab(self.experimentTab, _fromUtf8(""))
        self.verticalLayout_2.addWidget(self.mainTabWidget)
        ApplicationWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(ApplicationWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1024, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.menubar.setFont(font)
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setTitle(QtGui.QApplication.translate("ApplicationWindow", "&File", None, QtGui.QApplication.UnicodeUTF8))
        self.menuFile.setObjectName(_fromUtf8("menuFile"))
        self.menu_Help = QtGui.QMenu(self.menubar)
        self.menu_Help.setTitle(QtGui.QApplication.translate("ApplicationWindow", "&Help", None, QtGui.QApplication.UnicodeUTF8))
        self.menu_Help.setObjectName(_fromUtf8("menu_Help"))
        self.menuView = QtGui.QMenu(self.menubar)
        self.menuView.setTitle(QtGui.QApplication.translate("ApplicationWindow", "View", None, QtGui.QApplication.UnicodeUTF8))
        self.menuView.setObjectName(_fromUtf8("menuView"))
        self.menuLogging_Level = QtGui.QMenu(self.menuView)
        self.menuLogging_Level.setTitle(QtGui.QApplication.translate("ApplicationWindow", "Logging level", None, QtGui.QApplication.UnicodeUTF8))
        self.menuLogging_Level.setObjectName(_fromUtf8("menuLogging_Level"))
        self.menuEdit = QtGui.QMenu(self.menubar)
        self.menuEdit.setTitle(QtGui.QApplication.translate("ApplicationWindow", "Edit", None, QtGui.QApplication.UnicodeUTF8))
        self.menuEdit.setObjectName(_fromUtf8("menuEdit"))
        ApplicationWindow.setMenuBar(self.menubar)
        self.logWindow = QtGui.QDockWidget(ApplicationWindow)
        self.logWindow.setFeatures(QtGui.QDockWidget.DockWidgetMovable)
        self.logWindow.setAllowedAreas(QtCore.Qt.BottomDockWidgetArea|QtCore.Qt.RightDockWidgetArea)
        self.logWindow.setWindowTitle(QtGui.QApplication.translate("ApplicationWindow", "Log", None, QtGui.QApplication.UnicodeUTF8))
        self.logWindow.setObjectName(_fromUtf8("logWindow"))
        self.dockWidgetContents = QtGui.QWidget()
        self.dockWidgetContents.setObjectName(_fromUtf8("dockWidgetContents"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.dockWidgetContents)
        self.horizontalLayout.setMargin(0)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.logView = LogWidget(self.dockWidgetContents)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("MS Shell Dlg 2"))
        font.setPointSize(10)
        self.logView.setFont(font)
        self.logView.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.logView.setSelectionMode(QtGui.QAbstractItemView.SingleSelection)
        self.logView.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.logView.setIconSize(QtCore.QSize(18, 18))
        self.logView.setShowGrid(False)
        self.logView.setCornerButtonEnabled(False)
        self.logView.setColumnCount(3)
        self.logView.setObjectName(_fromUtf8("logView"))
        self.logView.setRowCount(0)
        self.logView.horizontalHeader().setCascadingSectionResizes(False)
        self.logView.horizontalHeader().setMinimumSectionSize(1)
        self.logView.horizontalHeader().setSortIndicatorShown(False)
        self.logView.horizontalHeader().setStretchLastSection(True)
        self.logView.verticalHeader().setVisible(False)
        self.logView.verticalHeader().setCascadingSectionResizes(False)
        self.logView.verticalHeader().setDefaultSectionSize(17)
        self.horizontalLayout.addWidget(self.logView)
        self.logWindow.setWidget(self.dockWidgetContents)
        ApplicationWindow.addDockWidget(QtCore.Qt.DockWidgetArea(2), self.logWindow)
        self.experimentViewer = QtGui.QDockWidget(ApplicationWindow)
        self.experimentViewer.setFeatures(QtGui.QDockWidget.DockWidgetMovable)
        self.experimentViewer.setAllowedAreas(QtCore.Qt.BottomDockWidgetArea|QtCore.Qt.RightDockWidgetArea)
        self.experimentViewer.setWindowTitle(QtGui.QApplication.translate("ApplicationWindow", "Experiment", None, QtGui.QApplication.UnicodeUTF8))
        self.experimentViewer.setObjectName(_fromUtf8("experimentViewer"))
        self.dockWidgetContents_2 = QtGui.QWidget()
        self.dockWidgetContents_2.setObjectName(_fromUtf8("dockWidgetContents_2"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout(self.dockWidgetContents_2)
        self.horizontalLayout_4.setMargin(0)
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.mainDropWidget = DropWidget(self.dockWidgetContents_2)
        self.mainDropWidget.setObjectName(_fromUtf8("mainDropWidget"))
        self.verticalLayout.addWidget(self.mainDropWidget)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.horizontalLayout_4.addLayout(self.verticalLayout)
        self.experimentViewer.setWidget(self.dockWidgetContents_2)
        ApplicationWindow.addDockWidget(QtCore.Qt.DockWidgetArea(2), self.experimentViewer)
        self.resultViewer = QtGui.QDockWidget(ApplicationWindow)
        self.resultViewer.setFeatures(QtGui.QDockWidget.DockWidgetMovable)
        self.resultViewer.setAllowedAreas(QtCore.Qt.RightDockWidgetArea|QtCore.Qt.TopDockWidgetArea)
        self.resultViewer.setWindowTitle(QtGui.QApplication.translate("ApplicationWindow", "Result", None, QtGui.QApplication.UnicodeUTF8))
        self.resultViewer.setObjectName(_fromUtf8("resultViewer"))
        self.resultViewerWidget = QtGui.QWidget()
        self.resultViewerWidget.setObjectName(_fromUtf8("resultViewerWidget"))
        self.resultVerticalLayout = QtGui.QVBoxLayout(self.resultViewerWidget)
        self.resultVerticalLayout.setMargin(0)
        self.resultVerticalLayout.setObjectName(_fromUtf8("resultVerticalLayout"))
        self.resultViewer.setWidget(self.resultViewerWidget)
        ApplicationWindow.addDockWidget(QtCore.Qt.DockWidgetArea(2), self.resultViewer)
        self.action_Quit = QtGui.QAction(ApplicationWindow)
        self.action_Quit.setText(QtGui.QApplication.translate("ApplicationWindow", "&Quit", None, QtGui.QApplication.UnicodeUTF8))
        self.action_Quit.setShortcut(QtGui.QApplication.translate("ApplicationWindow", "Ctrl+Q", None, QtGui.QApplication.UnicodeUTF8))
        self.action_Quit.setObjectName(_fromUtf8("action_Quit"))
        self.action_About = QtGui.QAction(ApplicationWindow)
        self.action_About.setText(QtGui.QApplication.translate("ApplicationWindow", "&About", None, QtGui.QApplication.UnicodeUTF8))
        self.action_About.setObjectName(_fromUtf8("action_About"))
        self.actionErrors_only = QtGui.QAction(ApplicationWindow)
        self.actionErrors_only.setText(QtGui.QApplication.translate("ApplicationWindow", "Errors only", None, QtGui.QApplication.UnicodeUTF8))
        self.actionErrors_only.setObjectName(_fromUtf8("actionErrors_only"))
        self.actionInfo = QtGui.QAction(ApplicationWindow)
        self.actionInfo.setText(QtGui.QApplication.translate("ApplicationWindow", "Info", None, QtGui.QApplication.UnicodeUTF8))
        self.actionInfo.setObjectName(_fromUtf8("actionInfo"))
        self.actionDebug = QtGui.QAction(ApplicationWindow)
        self.actionDebug.setText(QtGui.QApplication.translate("ApplicationWindow", "Debug", None, QtGui.QApplication.UnicodeUTF8))
        self.actionDebug.setObjectName(_fromUtf8("actionDebug"))
        self.actionTree_on_top = QtGui.QAction(ApplicationWindow)
        self.actionTree_on_top.setText(QtGui.QApplication.translate("ApplicationWindow", "Tree on &top", None, QtGui.QApplication.UnicodeUTF8))
        self.actionTree_on_top.setShortcut(QtGui.QApplication.translate("ApplicationWindow", "Ctrl+2", None, QtGui.QApplication.UnicodeUTF8))
        self.actionTree_on_top.setObjectName(_fromUtf8("actionTree_on_top"))
        self.actionTree_left = QtGui.QAction(ApplicationWindow)
        self.actionTree_left.setText(QtGui.QApplication.translate("ApplicationWindow", "Tree &left", None, QtGui.QApplication.UnicodeUTF8))
        self.actionTree_left.setShortcut(QtGui.QApplication.translate("ApplicationWindow", "Ctrl+1", None, QtGui.QApplication.UnicodeUTF8))
        self.actionTree_left.setObjectName(_fromUtf8("actionTree_left"))
        self.menuFile.addAction(self.action_Quit)
        self.menu_Help.addAction(self.action_About)
        self.menuLogging_Level.addAction(self.actionErrors_only)
        self.menuLogging_Level.addAction(self.actionInfo)
        self.menuLogging_Level.addAction(self.actionDebug)
        self.menuView.addAction(self.menuLogging_Level.menuAction())
        self.menuView.addSeparator()
        self.menuView.addAction(self.actionTree_left)
        self.menuView.addAction(self.actionTree_on_top)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuEdit.menuAction())
        self.menubar.addAction(self.menuView.menuAction())
        self.menubar.addAction(self.menu_Help.menuAction())

        self.retranslateUi(ApplicationWindow)
        self.mainTabWidget.setCurrentIndex(0)
        QtCore.QObject.connect(self.action_Quit, QtCore.SIGNAL(_fromUtf8("triggered()")), ApplicationWindow.close)
        QtCore.QMetaObject.connectSlotsByName(ApplicationWindow)

    def retranslateUi(self, ApplicationWindow):
        self.mainTabWidget.setTabText(self.mainTabWidget.indexOf(self.resultsTab), QtGui.QApplication.translate("ApplicationWindow", "Results", None, QtGui.QApplication.UnicodeUTF8))
        self.mainTabWidget.setTabText(self.mainTabWidget.indexOf(self.experimentTab), QtGui.QApplication.translate("ApplicationWindow", "Experiments", None, QtGui.QApplication.UnicodeUTF8))

from gui.experimenttreewidget import ExperimentTreeWidget
from gui.logwidget import LogWidget
from gui.dropwidget_controller import DropWidget
from gui.experimentresultcollection_controller import ExperimentResultCollectionController
import icons_rc
