# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'experimentresultcollection_view.ui'
#
# Created: Fri Apr 20 17:34:59 2012
#      by: PyQt4 UI code generator 4.8.5
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_ExperimentResultCollection(object):
    def setupUi(self, ExperimentResultCollection):
        ExperimentResultCollection.setObjectName(_fromUtf8("ExperimentResultCollection"))
        ExperimentResultCollection.resize(557, 546)
        ExperimentResultCollection.setWindowTitle(QtGui.QApplication.translate("ExperimentResultCollection", "ResultTree", None, QtGui.QApplication.UnicodeUTF8))
        self.gridLayout = QtGui.QGridLayout(ExperimentResultCollection)
        self.gridLayout.setMargin(0)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.theTreeWidget = QtGui.QTreeWidget(ExperimentResultCollection)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("MS Shell Dlg 2"))
        font.setPointSize(10)
        self.theTreeWidget.setFont(font)
        self.theTreeWidget.setObjectName(_fromUtf8("theTreeWidget"))
        self.theTreeWidget.headerItem().setText(0, QtGui.QApplication.translate("ExperimentResultCollection", "Name", None, QtGui.QApplication.UnicodeUTF8))
        self.theTreeWidget.headerItem().setText(1, QtGui.QApplication.translate("ExperimentResultCollection", "Experiment", None, QtGui.QApplication.UnicodeUTF8))
        self.theTreeWidget.headerItem().setText(2, QtGui.QApplication.translate("ExperimentResultCollection", "Date", None, QtGui.QApplication.UnicodeUTF8))
        self.theTreeWidget.headerItem().setText(3, QtGui.QApplication.translate("ExperimentResultCollection", "Operator", None, QtGui.QApplication.UnicodeUTF8))
        self.theTreeWidget.headerItem().setText(4, QtGui.QApplication.translate("ExperimentResultCollection", "DUT", None, QtGui.QApplication.UnicodeUTF8))
        item_0 = QtGui.QTreeWidgetItem(self.theTreeWidget)
        self.theTreeWidget.topLevelItem(0).setText(0, QtGui.QApplication.translate("ExperimentResultCollection", "All", None, QtGui.QApplication.UnicodeUTF8))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/results/Filter.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        item_0.setIcon(0, icon)
        self.theTreeWidget.topLevelItem(0).setText(2, QtGui.QApplication.translate("ExperimentResultCollection", "*", None, QtGui.QApplication.UnicodeUTF8))
        self.theTreeWidget.topLevelItem(0).setText(3, QtGui.QApplication.translate("ExperimentResultCollection", "*", None, QtGui.QApplication.UnicodeUTF8))
        self.theTreeWidget.topLevelItem(0).setText(4, QtGui.QApplication.translate("ExperimentResultCollection", "*", None, QtGui.QApplication.UnicodeUTF8))
        item_0 = QtGui.QTreeWidgetItem(self.theTreeWidget)
        self.theTreeWidget.topLevelItem(1).setText(0, QtGui.QApplication.translate("ExperimentResultCollection", "Templates", None, QtGui.QApplication.UnicodeUTF8))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8(":/results/Folder.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        item_0.setIcon(0, icon1)
        item_1 = QtGui.QTreeWidgetItem(item_0)
        self.theTreeWidget.topLevelItem(1).child(0).setText(0, QtGui.QApplication.translate("ExperimentResultCollection", "Simple DPI", None, QtGui.QApplication.UnicodeUTF8))
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8(":/results/ExperimentTemplate.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        item_1.setIcon(0, icon2)
        self.theTreeWidget.topLevelItem(1).child(0).setText(1, QtGui.QApplication.translate("ExperimentResultCollection", "DPI", None, QtGui.QApplication.UnicodeUTF8))
        item_0 = QtGui.QTreeWidgetItem(self.theTreeWidget)
        self.theTreeWidget.topLevelItem(2).setText(0, QtGui.QApplication.translate("ExperimentResultCollection", "Sjoerd", None, QtGui.QApplication.UnicodeUTF8))
        item_0.setIcon(0, icon1)
        item_1 = QtGui.QTreeWidgetItem(item_0)
        self.theTreeWidget.topLevelItem(2).child(0).setText(0, QtGui.QApplication.translate("ExperimentResultCollection", "All", None, QtGui.QApplication.UnicodeUTF8))
        item_1.setIcon(0, icon)
        self.theTreeWidget.topLevelItem(2).child(0).setText(2, QtGui.QApplication.translate("ExperimentResultCollection", "*", None, QtGui.QApplication.UnicodeUTF8))
        self.theTreeWidget.topLevelItem(2).child(0).setText(3, QtGui.QApplication.translate("ExperimentResultCollection", "Sjoerd", None, QtGui.QApplication.UnicodeUTF8))
        self.theTreeWidget.topLevelItem(2).child(0).setText(4, QtGui.QApplication.translate("ExperimentResultCollection", "*", None, QtGui.QApplication.UnicodeUTF8))
        item_1 = QtGui.QTreeWidgetItem(item_0)
        self.theTreeWidget.topLevelItem(2).child(1).setText(0, QtGui.QApplication.translate("ExperimentResultCollection", "Regulator", None, QtGui.QApplication.UnicodeUTF8))
        item_1.setIcon(0, icon)
        self.theTreeWidget.topLevelItem(2).child(1).setText(2, QtGui.QApplication.translate("ExperimentResultCollection", "*", None, QtGui.QApplication.UnicodeUTF8))
        self.theTreeWidget.topLevelItem(2).child(1).setText(3, QtGui.QApplication.translate("ExperimentResultCollection", "Sjoerd", None, QtGui.QApplication.UnicodeUTF8))
        self.theTreeWidget.topLevelItem(2).child(1).setText(4, QtGui.QApplication.translate("ExperimentResultCollection", "{LM7805,L4949}", None, QtGui.QApplication.UnicodeUTF8))
        item_1 = QtGui.QTreeWidgetItem(item_0)
        self.theTreeWidget.topLevelItem(2).child(2).setText(0, QtGui.QApplication.translate("ExperimentResultCollection", "x-DPI", None, QtGui.QApplication.UnicodeUTF8))
        item_1.setIcon(0, icon1)
        item_2 = QtGui.QTreeWidgetItem(item_1)
        self.theTreeWidget.topLevelItem(2).child(2).child(0).setText(0, QtGui.QApplication.translate("ExperimentResultCollection", "x-DPI", None, QtGui.QApplication.UnicodeUTF8))
        item_2.setIcon(0, icon2)
        self.theTreeWidget.topLevelItem(2).child(2).child(0).setText(1, QtGui.QApplication.translate("ExperimentResultCollection", "DPI", None, QtGui.QApplication.UnicodeUTF8))
        item_2 = QtGui.QTreeWidgetItem(item_1)
        self.theTreeWidget.topLevelItem(2).child(2).child(1).setText(0, QtGui.QApplication.translate("ExperimentResultCollection", "x-DPI", None, QtGui.QApplication.UnicodeUTF8))
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(_fromUtf8(":/results/ExperimentResult.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        item_2.setIcon(0, icon3)
        self.theTreeWidget.topLevelItem(2).child(2).child(1).setText(1, QtGui.QApplication.translate("ExperimentResultCollection", "DPI", None, QtGui.QApplication.UnicodeUTF8))
        self.theTreeWidget.topLevelItem(2).child(2).child(1).setText(2, QtGui.QApplication.translate("ExperimentResultCollection", "Yesterday", None, QtGui.QApplication.UnicodeUTF8))
        self.theTreeWidget.topLevelItem(2).child(2).child(1).setText(3, QtGui.QApplication.translate("ExperimentResultCollection", "Sjoerd", None, QtGui.QApplication.UnicodeUTF8))
        self.theTreeWidget.topLevelItem(2).child(2).child(1).setText(4, QtGui.QApplication.translate("ExperimentResultCollection", "LM7805", None, QtGui.QApplication.UnicodeUTF8))
        item_0 = QtGui.QTreeWidgetItem(self.theTreeWidget)
        self.theTreeWidget.topLevelItem(3).setText(0, QtGui.QApplication.translate("ExperimentResultCollection", "Mohamed", None, QtGui.QApplication.UnicodeUTF8))
        item_0.setIcon(0, icon1)
        item_1 = QtGui.QTreeWidgetItem(item_0)
        self.theTreeWidget.topLevelItem(3).child(0).setText(0, QtGui.QApplication.translate("ExperimentResultCollection", "All", None, QtGui.QApplication.UnicodeUTF8))
        item_1.setIcon(0, icon)
        self.theTreeWidget.topLevelItem(3).child(0).setText(2, QtGui.QApplication.translate("ExperimentResultCollection", "*", None, QtGui.QApplication.UnicodeUTF8))
        self.theTreeWidget.topLevelItem(3).child(0).setText(3, QtGui.QApplication.translate("ExperimentResultCollection", "Mohamed", None, QtGui.QApplication.UnicodeUTF8))
        self.theTreeWidget.topLevelItem(3).child(0).setText(4, QtGui.QApplication.translate("ExperimentResultCollection", "*", None, QtGui.QApplication.UnicodeUTF8))
        item_1 = QtGui.QTreeWidgetItem(item_0)
        self.theTreeWidget.topLevelItem(3).child(1).setText(0, QtGui.QApplication.translate("ExperimentResultCollection", "Memory", None, QtGui.QApplication.UnicodeUTF8))
        item_1.setIcon(0, icon1)
        item_2 = QtGui.QTreeWidgetItem(item_1)
        self.theTreeWidget.topLevelItem(3).child(1).child(0).setText(0, QtGui.QApplication.translate("ExperimentResultCollection", "DPI", None, QtGui.QApplication.UnicodeUTF8))
        item_2.setIcon(0, icon3)
        self.theTreeWidget.topLevelItem(3).child(1).child(0).setText(1, QtGui.QApplication.translate("ExperimentResultCollection", "DPI", None, QtGui.QApplication.UnicodeUTF8))
        self.theTreeWidget.topLevelItem(3).child(1).child(0).setText(3, QtGui.QApplication.translate("ExperimentResultCollection", "Mohamed", None, QtGui.QApplication.UnicodeUTF8))
        self.gridLayout.addWidget(self.theTreeWidget, 0, 0, 1, 4)
        self.addFolder = QtGui.QPushButton(ExperimentResultCollection)
        self.addFolder.setText(_fromUtf8(""))
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(_fromUtf8(":/results/AddFolder.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.addFolder.setIcon(icon4)
        self.addFolder.setIconSize(QtCore.QSize(32, 16))
        self.addFolder.setObjectName(_fromUtf8("addFolder"))
        self.gridLayout.addWidget(self.addFolder, 1, 0, 1, 1)
        self.addFilter = QtGui.QPushButton(ExperimentResultCollection)
        self.addFilter.setText(_fromUtf8(""))
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(_fromUtf8(":/results/AddFilter.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.addFilter.setIcon(icon5)
        self.addFilter.setIconSize(QtCore.QSize(32, 16))
        self.addFilter.setObjectName(_fromUtf8("addFilter"))
        self.gridLayout.addWidget(self.addFilter, 1, 1, 1, 1)
        spacerItem = QtGui.QSpacerItem(145, 17, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 1, 2, 1, 1)
        self.deleteItem = QtGui.QPushButton(ExperimentResultCollection)
        self.deleteItem.setText(_fromUtf8(""))
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(_fromUtf8(":/results/Delete.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.deleteItem.setIcon(icon6)
        self.deleteItem.setIconSize(QtCore.QSize(16, 16))
        self.deleteItem.setObjectName(_fromUtf8("deleteItem"))
        self.gridLayout.addWidget(self.deleteItem, 1, 3, 1, 1)

        self.retranslateUi(ExperimentResultCollection)
        QtCore.QMetaObject.connectSlotsByName(ExperimentResultCollection)

    def retranslateUi(self, ExperimentResultCollection):
        __sortingEnabled = self.theTreeWidget.isSortingEnabled()
        self.theTreeWidget.setSortingEnabled(False)
        self.theTreeWidget.setSortingEnabled(__sortingEnabled)

import icons_rc
