# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mockup_view3.ui'
#
# Created: Fri Apr 20 11:40:33 2012
#      by: PyQt4 UI code generator 4.8.5
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(1024, 768)
        font = QtGui.QFont()
        font.setPointSize(10)
        MainWindow.setFont(font)
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "EMC Testbench", None, QtGui.QApplication.UnicodeUTF8))
        MainWindow.setDockNestingEnabled(True)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_3.setMargin(0)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.tabWidget = QtGui.QTabWidget(self.centralwidget)
        self.tabWidget.setTabPosition(QtGui.QTabWidget.South)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.gridLayout_2 = QtGui.QGridLayout(self.tab)
        self.gridLayout_2.setContentsMargins(3, 3, 3, 6)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.treeWidget_2 = QtGui.QTreeWidget(self.tab)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("MS Shell Dlg 2"))
        font.setPointSize(10)
        self.treeWidget_2.setFont(font)
        self.treeWidget_2.setObjectName(_fromUtf8("treeWidget_2"))
        self.treeWidget_2.headerItem().setText(0, QtGui.QApplication.translate("MainWindow", "Name", None, QtGui.QApplication.UnicodeUTF8))
        self.treeWidget_2.headerItem().setText(1, QtGui.QApplication.translate("MainWindow", "Experiment", None, QtGui.QApplication.UnicodeUTF8))
        self.treeWidget_2.headerItem().setText(2, QtGui.QApplication.translate("MainWindow", "Date", None, QtGui.QApplication.UnicodeUTF8))
        self.treeWidget_2.headerItem().setText(3, QtGui.QApplication.translate("MainWindow", "Operator", None, QtGui.QApplication.UnicodeUTF8))
        self.treeWidget_2.headerItem().setText(4, QtGui.QApplication.translate("MainWindow", "DUT", None, QtGui.QApplication.UnicodeUTF8))
        item_0 = QtGui.QTreeWidgetItem(self.treeWidget_2)
        self.treeWidget_2.topLevelItem(0).setText(0, QtGui.QApplication.translate("MainWindow", "All", None, QtGui.QApplication.UnicodeUTF8))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/results/Filter.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        item_0.setIcon(0, icon)
        self.treeWidget_2.topLevelItem(0).setText(2, QtGui.QApplication.translate("MainWindow", "*", None, QtGui.QApplication.UnicodeUTF8))
        self.treeWidget_2.topLevelItem(0).setText(3, QtGui.QApplication.translate("MainWindow", "*", None, QtGui.QApplication.UnicodeUTF8))
        self.treeWidget_2.topLevelItem(0).setText(4, QtGui.QApplication.translate("MainWindow", "*", None, QtGui.QApplication.UnicodeUTF8))
        item_0 = QtGui.QTreeWidgetItem(self.treeWidget_2)
        self.treeWidget_2.topLevelItem(1).setText(0, QtGui.QApplication.translate("MainWindow", "Templates", None, QtGui.QApplication.UnicodeUTF8))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8(":/results/Folder.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        item_0.setIcon(0, icon1)
        item_1 = QtGui.QTreeWidgetItem(item_0)
        self.treeWidget_2.topLevelItem(1).child(0).setText(0, QtGui.QApplication.translate("MainWindow", "Simple DPI", None, QtGui.QApplication.UnicodeUTF8))
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8(":/results/ExperimentTemplate.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        item_1.setIcon(0, icon2)
        self.treeWidget_2.topLevelItem(1).child(0).setText(1, QtGui.QApplication.translate("MainWindow", "DPI", None, QtGui.QApplication.UnicodeUTF8))
        item_0 = QtGui.QTreeWidgetItem(self.treeWidget_2)
        self.treeWidget_2.topLevelItem(2).setText(0, QtGui.QApplication.translate("MainWindow", "Sjoerd", None, QtGui.QApplication.UnicodeUTF8))
        item_0.setIcon(0, icon1)
        item_1 = QtGui.QTreeWidgetItem(item_0)
        self.treeWidget_2.topLevelItem(2).child(0).setText(0, QtGui.QApplication.translate("MainWindow", "All", None, QtGui.QApplication.UnicodeUTF8))
        item_1.setIcon(0, icon)
        self.treeWidget_2.topLevelItem(2).child(0).setText(2, QtGui.QApplication.translate("MainWindow", "*", None, QtGui.QApplication.UnicodeUTF8))
        self.treeWidget_2.topLevelItem(2).child(0).setText(3, QtGui.QApplication.translate("MainWindow", "Sjoerd", None, QtGui.QApplication.UnicodeUTF8))
        self.treeWidget_2.topLevelItem(2).child(0).setText(4, QtGui.QApplication.translate("MainWindow", "*", None, QtGui.QApplication.UnicodeUTF8))
        item_1 = QtGui.QTreeWidgetItem(item_0)
        self.treeWidget_2.topLevelItem(2).child(1).setText(0, QtGui.QApplication.translate("MainWindow", "Regulator", None, QtGui.QApplication.UnicodeUTF8))
        item_1.setIcon(0, icon)
        self.treeWidget_2.topLevelItem(2).child(1).setText(2, QtGui.QApplication.translate("MainWindow", "*", None, QtGui.QApplication.UnicodeUTF8))
        self.treeWidget_2.topLevelItem(2).child(1).setText(3, QtGui.QApplication.translate("MainWindow", "Sjoerd", None, QtGui.QApplication.UnicodeUTF8))
        self.treeWidget_2.topLevelItem(2).child(1).setText(4, QtGui.QApplication.translate("MainWindow", "{LM7805,L4949}", None, QtGui.QApplication.UnicodeUTF8))
        item_1 = QtGui.QTreeWidgetItem(item_0)
        self.treeWidget_2.topLevelItem(2).child(2).setText(0, QtGui.QApplication.translate("MainWindow", "x-DPI", None, QtGui.QApplication.UnicodeUTF8))
        item_1.setIcon(0, icon1)
        item_2 = QtGui.QTreeWidgetItem(item_1)
        self.treeWidget_2.topLevelItem(2).child(2).child(0).setText(0, QtGui.QApplication.translate("MainWindow", "x-DPI", None, QtGui.QApplication.UnicodeUTF8))
        item_2.setIcon(0, icon2)
        self.treeWidget_2.topLevelItem(2).child(2).child(0).setText(1, QtGui.QApplication.translate("MainWindow", "DPI", None, QtGui.QApplication.UnicodeUTF8))
        item_2 = QtGui.QTreeWidgetItem(item_1)
        self.treeWidget_2.topLevelItem(2).child(2).child(1).setText(0, QtGui.QApplication.translate("MainWindow", "x-DPI", None, QtGui.QApplication.UnicodeUTF8))
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(_fromUtf8(":/results/ExperimentResult.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        item_2.setIcon(0, icon3)
        self.treeWidget_2.topLevelItem(2).child(2).child(1).setText(1, QtGui.QApplication.translate("MainWindow", "DPI", None, QtGui.QApplication.UnicodeUTF8))
        self.treeWidget_2.topLevelItem(2).child(2).child(1).setText(2, QtGui.QApplication.translate("MainWindow", "Yesterday", None, QtGui.QApplication.UnicodeUTF8))
        self.treeWidget_2.topLevelItem(2).child(2).child(1).setText(3, QtGui.QApplication.translate("MainWindow", "Sjoerd", None, QtGui.QApplication.UnicodeUTF8))
        self.treeWidget_2.topLevelItem(2).child(2).child(1).setText(4, QtGui.QApplication.translate("MainWindow", "LM7805", None, QtGui.QApplication.UnicodeUTF8))
        item_0 = QtGui.QTreeWidgetItem(self.treeWidget_2)
        self.treeWidget_2.topLevelItem(3).setText(0, QtGui.QApplication.translate("MainWindow", "Mohamed", None, QtGui.QApplication.UnicodeUTF8))
        item_0.setIcon(0, icon1)
        item_1 = QtGui.QTreeWidgetItem(item_0)
        self.treeWidget_2.topLevelItem(3).child(0).setText(0, QtGui.QApplication.translate("MainWindow", "All", None, QtGui.QApplication.UnicodeUTF8))
        item_1.setIcon(0, icon)
        self.treeWidget_2.topLevelItem(3).child(0).setText(2, QtGui.QApplication.translate("MainWindow", "*", None, QtGui.QApplication.UnicodeUTF8))
        self.treeWidget_2.topLevelItem(3).child(0).setText(3, QtGui.QApplication.translate("MainWindow", "Mohamed", None, QtGui.QApplication.UnicodeUTF8))
        self.treeWidget_2.topLevelItem(3).child(0).setText(4, QtGui.QApplication.translate("MainWindow", "*", None, QtGui.QApplication.UnicodeUTF8))
        item_1 = QtGui.QTreeWidgetItem(item_0)
        self.treeWidget_2.topLevelItem(3).child(1).setText(0, QtGui.QApplication.translate("MainWindow", "Memory", None, QtGui.QApplication.UnicodeUTF8))
        item_1.setIcon(0, icon1)
        item_2 = QtGui.QTreeWidgetItem(item_1)
        self.treeWidget_2.topLevelItem(3).child(1).child(0).setText(0, QtGui.QApplication.translate("MainWindow", "DPI", None, QtGui.QApplication.UnicodeUTF8))
        item_2.setIcon(0, icon3)
        self.treeWidget_2.topLevelItem(3).child(1).child(0).setText(1, QtGui.QApplication.translate("MainWindow", "DPI", None, QtGui.QApplication.UnicodeUTF8))
        self.treeWidget_2.topLevelItem(3).child(1).child(0).setText(3, QtGui.QApplication.translate("MainWindow", "Mohamed", None, QtGui.QApplication.UnicodeUTF8))
        self.gridLayout_2.addWidget(self.treeWidget_2, 0, 0, 1, 4)
        self.pushButton = QtGui.QPushButton(self.tab)
        self.pushButton.setText(_fromUtf8(""))
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(_fromUtf8(":/results/AddFolder.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton.setIcon(icon4)
        self.pushButton.setIconSize(QtCore.QSize(32, 16))
        self.pushButton.setObjectName(_fromUtf8("pushButton"))
        self.gridLayout_2.addWidget(self.pushButton, 1, 0, 1, 1)
        self.pushButton_2 = QtGui.QPushButton(self.tab)
        self.pushButton_2.setText(_fromUtf8(""))
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(_fromUtf8(":/results/AddFilter.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_2.setIcon(icon5)
        self.pushButton_2.setIconSize(QtCore.QSize(32, 16))
        self.pushButton_2.setObjectName(_fromUtf8("pushButton_2"))
        self.gridLayout_2.addWidget(self.pushButton_2, 1, 1, 1, 1)
        spacerItem = QtGui.QSpacerItem(56, 17, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem, 1, 2, 1, 1)
        self.pushButton_3 = QtGui.QPushButton(self.tab)
        self.pushButton_3.setText(_fromUtf8(""))
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(_fromUtf8(":/results/Delete.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_3.setIcon(icon6)
        self.pushButton_3.setIconSize(QtCore.QSize(16, 16))
        self.pushButton_3.setObjectName(_fromUtf8("pushButton_3"))
        self.gridLayout_2.addWidget(self.pushButton_3, 1, 3, 1, 1)
        self.tabWidget.addTab(self.tab, _fromUtf8(""))
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName(_fromUtf8("tab_2"))
        self.gridLayout_3 = QtGui.QGridLayout(self.tab_2)
        self.gridLayout_3.setMargin(3)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.treeWidget = QtGui.QTreeWidget(self.tab_2)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("MS Shell Dlg 2"))
        font.setPointSize(10)
        self.treeWidget.setFont(font)
        self.treeWidget.setObjectName(_fromUtf8("treeWidget"))
        self.treeWidget.headerItem().setText(0, QtGui.QApplication.translate("MainWindow", "1", None, QtGui.QApplication.UnicodeUTF8))
        item_0 = QtGui.QTreeWidgetItem(self.treeWidget)
        self.treeWidget.topLevelItem(0).setText(0, QtGui.QApplication.translate("MainWindow", "Devices", None, QtGui.QApplication.UnicodeUTF8))
        item_1 = QtGui.QTreeWidgetItem(item_0)
        self.treeWidget.topLevelItem(0).child(0).setText(0, QtGui.QApplication.translate("MainWindow", "Agilent L4411A", None, QtGui.QApplication.UnicodeUTF8))
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(_fromUtf8(":/devices/Multimeter.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        item_1.setIcon(0, icon7)
        item_2 = QtGui.QTreeWidgetItem(item_1)
        self.treeWidget.topLevelItem(0).child(0).child(0).setText(0, QtGui.QApplication.translate("MainWindow", "Voltage", None, QtGui.QApplication.UnicodeUTF8))
        item_3 = QtGui.QTreeWidgetItem(item_2)
        self.treeWidget.topLevelItem(0).child(0).child(0).child(0).setText(0, QtGui.QApplication.translate("MainWindow", "Average voltage", None, QtGui.QApplication.UnicodeUTF8))
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(_fromUtf8(":/results/Experiment.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        item_3.setIcon(0, icon8)
        item_3 = QtGui.QTreeWidgetItem(item_2)
        self.treeWidget.topLevelItem(0).child(0).child(0).child(1).setText(0, QtGui.QApplication.translate("MainWindow", "RMS voltage", None, QtGui.QApplication.UnicodeUTF8))
        item_3.setIcon(0, icon8)
        item_2 = QtGui.QTreeWidgetItem(item_1)
        self.treeWidget.topLevelItem(0).child(0).child(1).setText(0, QtGui.QApplication.translate("MainWindow", "Current", None, QtGui.QApplication.UnicodeUTF8))
        item_3 = QtGui.QTreeWidgetItem(item_2)
        self.treeWidget.topLevelItem(0).child(0).child(1).child(0).setText(0, QtGui.QApplication.translate("MainWindow", "Average current", None, QtGui.QApplication.UnicodeUTF8))
        item_3.setIcon(0, icon8)
        item_1 = QtGui.QTreeWidgetItem(item_0)
        self.treeWidget.topLevelItem(0).child(1).setText(0, QtGui.QApplication.translate("MainWindow", "Agilent DSO6014L", None, QtGui.QApplication.UnicodeUTF8))
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(_fromUtf8(":/devices/Oscilloscope.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        item_1.setIcon(0, icon9)
        item_2 = QtGui.QTreeWidgetItem(item_1)
        self.treeWidget.topLevelItem(0).child(1).child(0).setText(0, QtGui.QApplication.translate("MainWindow", "Voltage", None, QtGui.QApplication.UnicodeUTF8))
        item_3 = QtGui.QTreeWidgetItem(item_2)
        self.treeWidget.topLevelItem(0).child(1).child(0).child(0).setText(0, QtGui.QApplication.translate("MainWindow", "Average voltage", None, QtGui.QApplication.UnicodeUTF8))
        item_3.setIcon(0, icon8)
        item_2 = QtGui.QTreeWidgetItem(item_1)
        self.treeWidget.topLevelItem(0).child(1).child(1).setText(0, QtGui.QApplication.translate("MainWindow", "Frequency", None, QtGui.QApplication.UnicodeUTF8))
        item_2.setIcon(0, icon8)
        item_1 = QtGui.QTreeWidgetItem(item_0)
        self.treeWidget.topLevelItem(0).child(2).setText(0, QtGui.QApplication.translate("MainWindow", "Agilent 86100A/54754A", None, QtGui.QApplication.UnicodeUTF8))
        item_1.setIcon(0, icon9)
        item_1 = QtGui.QTreeWidgetItem(item_0)
        self.treeWidget.topLevelItem(0).child(3).setText(0, QtGui.QApplication.translate("MainWindow", "Agilent E4419B", None, QtGui.QApplication.UnicodeUTF8))
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap(_fromUtf8(":/devices/WattMeter.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        item_1.setIcon(0, icon10)
        item_2 = QtGui.QTreeWidgetItem(item_1)
        self.treeWidget.topLevelItem(0).child(3).child(0).setText(0, QtGui.QApplication.translate("MainWindow", "Power", None, QtGui.QApplication.UnicodeUTF8))
        item_2.setIcon(0, icon8)
        item_1 = QtGui.QTreeWidgetItem(item_0)
        self.treeWidget.topLevelItem(0).child(4).setText(0, QtGui.QApplication.translate("MainWindow", "Agilent 53220A", None, QtGui.QApplication.UnicodeUTF8))
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap(_fromUtf8(":/devices/Measurer.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        item_1.setIcon(0, icon11)
        item_1 = QtGui.QTreeWidgetItem(item_0)
        self.treeWidget.topLevelItem(0).child(5).setText(0, QtGui.QApplication.translate("MainWindow", "Agilent N9010A", None, QtGui.QApplication.UnicodeUTF8))
        icon12 = QtGui.QIcon()
        icon12.addPixmap(QtGui.QPixmap(_fromUtf8(":/devices/SpectrumAnalyzer.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        item_1.setIcon(0, icon12)
        item_1 = QtGui.QTreeWidgetItem(item_0)
        self.treeWidget.topLevelItem(0).child(6).setText(0, QtGui.QApplication.translate("MainWindow", "HP 8720C", None, QtGui.QApplication.UnicodeUTF8))
        item_1.setIcon(0, icon11)
        item_1 = QtGui.QTreeWidgetItem(item_0)
        self.treeWidget.topLevelItem(0).child(7).setText(0, QtGui.QApplication.translate("MainWindow", "Agilent N5247A", None, QtGui.QApplication.UnicodeUTF8))
        item_1.setIcon(0, icon11)
        item_1 = QtGui.QTreeWidgetItem(item_0)
        self.treeWidget.topLevelItem(0).child(8).setText(0, QtGui.QApplication.translate("MainWindow", "Agilent L4490A", None, QtGui.QApplication.UnicodeUTF8))
        icon13 = QtGui.QIcon()
        icon13.addPixmap(QtGui.QPixmap(_fromUtf8(":/devices/Switch.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        item_1.setIcon(0, icon13)
        item_2 = QtGui.QTreeWidgetItem(item_1)
        self.treeWidget.topLevelItem(0).child(8).child(0).setText(0, QtGui.QApplication.translate("MainWindow", "State", None, QtGui.QApplication.UnicodeUTF8))
        item_2.setIcon(0, icon8)
        item_1 = QtGui.QTreeWidgetItem(item_0)
        self.treeWidget.topLevelItem(0).child(9).setText(0, QtGui.QApplication.translate("MainWindow", "Prana AP32DT120", None, QtGui.QApplication.UnicodeUTF8))
        icon14 = QtGui.QIcon()
        icon14.addPixmap(QtGui.QPixmap(_fromUtf8(":/devices/Amplifier.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        item_1.setIcon(0, icon14)
        item_2 = QtGui.QTreeWidgetItem(item_1)
        self.treeWidget.topLevelItem(0).child(9).child(0).setText(0, QtGui.QApplication.translate("MainWindow", "State", None, QtGui.QApplication.UnicodeUTF8))
        item_2.setIcon(0, icon8)
        item_1 = QtGui.QTreeWidgetItem(item_0)
        self.treeWidget.topLevelItem(0).child(10).setText(0, QtGui.QApplication.translate("MainWindow", "Milmega AS0104-30/30", None, QtGui.QApplication.UnicodeUTF8))
        item_1.setIcon(0, icon14)
        item_2 = QtGui.QTreeWidgetItem(item_1)
        self.treeWidget.topLevelItem(0).child(10).child(0).setText(0, QtGui.QApplication.translate("MainWindow", "State", None, QtGui.QApplication.UnicodeUTF8))
        item_2.setIcon(0, icon8)
        item_1 = QtGui.QTreeWidgetItem(item_0)
        self.treeWidget.topLevelItem(0).child(11).setText(0, QtGui.QApplication.translate("MainWindow", "NI PCI-6251", None, QtGui.QApplication.UnicodeUTF8))
        item_1.setIcon(0, icon11)
        item_1 = QtGui.QTreeWidgetItem(item_0)
        self.treeWidget.topLevelItem(0).child(12).setText(0, QtGui.QApplication.translate("MainWindow", "FTDI 2232H", None, QtGui.QApplication.UnicodeUTF8))
        icon15 = QtGui.QIcon()
        icon15.addPixmap(QtGui.QPixmap(_fromUtf8(":/devices/Stimulator.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        item_1.setIcon(0, icon15)
        item_1 = QtGui.QTreeWidgetItem(item_0)
        self.treeWidget.topLevelItem(0).child(13).setText(0, QtGui.QApplication.translate("MainWindow", "Newport ESP300", None, QtGui.QApplication.UnicodeUTF8))
        icon16 = QtGui.QIcon()
        icon16.addPixmap(QtGui.QPixmap(_fromUtf8(":/devices/Positioner.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        item_1.setIcon(0, icon16)
        item_2 = QtGui.QTreeWidgetItem(item_1)
        self.treeWidget.topLevelItem(0).child(13).child(0).setText(0, QtGui.QApplication.translate("MainWindow", "Position", None, QtGui.QApplication.UnicodeUTF8))
        item_2.setIcon(0, icon8)
        item_0 = QtGui.QTreeWidgetItem(self.treeWidget)
        self.treeWidget.topLevelItem(1).setText(0, QtGui.QApplication.translate("MainWindow", "Experiments", None, QtGui.QApplication.UnicodeUTF8))
        item_1 = QtGui.QTreeWidgetItem(item_0)
        self.treeWidget.topLevelItem(1).child(0).setText(0, QtGui.QApplication.translate("MainWindow", "Emission", None, QtGui.QApplication.UnicodeUTF8))
        item_2 = QtGui.QTreeWidgetItem(item_1)
        self.treeWidget.topLevelItem(1).child(0).child(0).setText(0, QtGui.QApplication.translate("MainWindow", "GTEM Emission", None, QtGui.QApplication.UnicodeUTF8))
        item_2.setIcon(0, icon8)
        item_1 = QtGui.QTreeWidgetItem(item_0)
        self.treeWidget.topLevelItem(1).child(1).setText(0, QtGui.QApplication.translate("MainWindow", "Immunity", None, QtGui.QApplication.UnicodeUTF8))
        item_2 = QtGui.QTreeWidgetItem(item_1)
        self.treeWidget.topLevelItem(1).child(1).child(0).setText(0, QtGui.QApplication.translate("MainWindow", "DPI", None, QtGui.QApplication.UnicodeUTF8))
        item_2.setIcon(0, icon8)
        item_2 = QtGui.QTreeWidgetItem(item_1)
        self.treeWidget.topLevelItem(1).child(1).child(1).setText(0, QtGui.QApplication.translate("MainWindow", "NFSI", None, QtGui.QApplication.UnicodeUTF8))
        item_2.setIcon(0, icon8)
        item_1 = QtGui.QTreeWidgetItem(item_0)
        self.treeWidget.topLevelItem(1).child(2).setText(0, QtGui.QApplication.translate("MainWindow", "Generic stimuli", None, QtGui.QApplication.UnicodeUTF8))
        item_2 = QtGui.QTreeWidgetItem(item_1)
        self.treeWidget.topLevelItem(1).child(2).child(0).setText(0, QtGui.QApplication.translate("MainWindow", "DC voltage", None, QtGui.QApplication.UnicodeUTF8))
        item_3 = QtGui.QTreeWidgetItem(item_2)
        self.treeWidget.topLevelItem(1).child(2).child(0).child(0).setText(0, QtGui.QApplication.translate("MainWindow", "N6700B", None, QtGui.QApplication.UnicodeUTF8))
        icon17 = QtGui.QIcon()
        icon17.addPixmap(QtGui.QPixmap(_fromUtf8(":/devices/PowerSupply.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        item_3.setIcon(0, icon17)
        item_2 = QtGui.QTreeWidgetItem(item_1)
        self.treeWidget.topLevelItem(1).child(2).child(1).setText(0, QtGui.QApplication.translate("MainWindow", "DC current", None, QtGui.QApplication.UnicodeUTF8))
        item_3 = QtGui.QTreeWidgetItem(item_2)
        self.treeWidget.topLevelItem(1).child(2).child(1).child(0).setText(0, QtGui.QApplication.translate("MainWindow", "N6700B", None, QtGui.QApplication.UnicodeUTF8))
        item_3.setIcon(0, icon17)
        item_2 = QtGui.QTreeWidgetItem(item_1)
        self.treeWidget.topLevelItem(1).child(2).child(2).setText(0, QtGui.QApplication.translate("MainWindow", "Control signals", None, QtGui.QApplication.UnicodeUTF8))
        item_3 = QtGui.QTreeWidgetItem(item_2)
        self.treeWidget.topLevelItem(1).child(2).child(2).child(0).setText(0, QtGui.QApplication.translate("MainWindow", "Agilent N6700B", None, QtGui.QApplication.UnicodeUTF8))
        item_3.setIcon(0, icon17)
        item_3 = QtGui.QTreeWidgetItem(item_2)
        self.treeWidget.topLevelItem(1).child(2).child(2).child(1).setText(0, QtGui.QApplication.translate("MainWindow", "Agilent L4490A", None, QtGui.QApplication.UnicodeUTF8))
        item_3.setIcon(0, icon13)
        item_3 = QtGui.QTreeWidgetItem(item_2)
        self.treeWidget.topLevelItem(1).child(2).child(2).child(2).setText(0, QtGui.QApplication.translate("MainWindow", "FTDI 2232H", None, QtGui.QApplication.UnicodeUTF8))
        item_3.setIcon(0, icon15)
        item_2 = QtGui.QTreeWidgetItem(item_1)
        self.treeWidget.topLevelItem(1).child(2).child(3).setText(0, QtGui.QApplication.translate("MainWindow", "Scalar data signals", None, QtGui.QApplication.UnicodeUTF8))
        item_3 = QtGui.QTreeWidgetItem(item_2)
        self.treeWidget.topLevelItem(1).child(2).child(3).child(0).setText(0, QtGui.QApplication.translate("MainWindow", "Periodic signals", None, QtGui.QApplication.UnicodeUTF8))
        item_4 = QtGui.QTreeWidgetItem(item_3)
        self.treeWidget.topLevelItem(1).child(2).child(3).child(0).child(0).setText(0, QtGui.QApplication.translate("MainWindow", "Agilent N5181A", None, QtGui.QApplication.UnicodeUTF8))
        icon18 = QtGui.QIcon()
        icon18.addPixmap(QtGui.QPixmap(_fromUtf8(":/devices/RfGenerator.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        item_4.setIcon(0, icon18)
        item_4 = QtGui.QTreeWidgetItem(item_3)
        self.treeWidget.topLevelItem(1).child(2).child(3).child(0).child(1).setText(0, QtGui.QApplication.translate("MainWindow", "Agilent 33220A top", None, QtGui.QApplication.UnicodeUTF8))
        icon19 = QtGui.QIcon()
        icon19.addPixmap(QtGui.QPixmap(_fromUtf8(":/devices/Generator.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        item_4.setIcon(0, icon19)
        item_4 = QtGui.QTreeWidgetItem(item_3)
        self.treeWidget.topLevelItem(1).child(2).child(3).child(0).child(2).setText(0, QtGui.QApplication.translate("MainWindow", "Agilent 33220A bottom", None, QtGui.QApplication.UnicodeUTF8))
        item_4.setIcon(0, icon19)
        item_4 = QtGui.QTreeWidgetItem(item_3)
        self.treeWidget.topLevelItem(1).child(2).child(3).child(0).child(3).setText(0, QtGui.QApplication.translate("MainWindow", "Agilent 33250A", None, QtGui.QApplication.UnicodeUTF8))
        item_4.setIcon(0, icon19)
        item_3 = QtGui.QTreeWidgetItem(item_2)
        self.treeWidget.topLevelItem(1).child(2).child(3).child(1).setText(0, QtGui.QApplication.translate("MainWindow", "One-shot signals", None, QtGui.QApplication.UnicodeUTF8))
        item_4 = QtGui.QTreeWidgetItem(item_3)
        self.treeWidget.topLevelItem(1).child(2).child(3).child(1).child(0).setText(0, QtGui.QApplication.translate("MainWindow", "Agilent 33220A top", None, QtGui.QApplication.UnicodeUTF8))
        item_4.setIcon(0, icon19)
        item_4 = QtGui.QTreeWidgetItem(item_3)
        self.treeWidget.topLevelItem(1).child(2).child(3).child(1).child(1).setText(0, QtGui.QApplication.translate("MainWindow", "Agilent 33220A bottom", None, QtGui.QApplication.UnicodeUTF8))
        item_4.setIcon(0, icon19)
        item_4 = QtGui.QTreeWidgetItem(item_3)
        self.treeWidget.topLevelItem(1).child(2).child(3).child(1).child(2).setText(0, QtGui.QApplication.translate("MainWindow", "Agilent 33250A", None, QtGui.QApplication.UnicodeUTF8))
        item_4.setIcon(0, icon19)
        item_3 = QtGui.QTreeWidgetItem(item_2)
        self.treeWidget.topLevelItem(1).child(2).child(3).child(2).setText(0, QtGui.QApplication.translate("MainWindow", "Noise", None, QtGui.QApplication.UnicodeUTF8))
        item_4 = QtGui.QTreeWidgetItem(item_3)
        self.treeWidget.topLevelItem(1).child(2).child(3).child(2).child(0).setText(0, QtGui.QApplication.translate("MainWindow", "Agilent 33220A top", None, QtGui.QApplication.UnicodeUTF8))
        item_4.setIcon(0, icon19)
        item_4 = QtGui.QTreeWidgetItem(item_3)
        self.treeWidget.topLevelItem(1).child(2).child(3).child(2).child(1).setText(0, QtGui.QApplication.translate("MainWindow", "Agilent 33220A bottom", None, QtGui.QApplication.UnicodeUTF8))
        item_4.setIcon(0, icon19)
        item_4 = QtGui.QTreeWidgetItem(item_3)
        self.treeWidget.topLevelItem(1).child(2).child(3).child(2).child(2).setText(0, QtGui.QApplication.translate("MainWindow", "Agilent 33250A", None, QtGui.QApplication.UnicodeUTF8))
        item_4.setIcon(0, icon19)
        item_2 = QtGui.QTreeWidgetItem(item_1)
        self.treeWidget.topLevelItem(1).child(2).child(4).setText(0, QtGui.QApplication.translate("MainWindow", "Test vectors", None, QtGui.QApplication.UnicodeUTF8))
        item_3 = QtGui.QTreeWidgetItem(item_2)
        self.treeWidget.topLevelItem(1).child(2).child(4).child(0).setText(0, QtGui.QApplication.translate("MainWindow", "Serial", None, QtGui.QApplication.UnicodeUTF8))
        item_4 = QtGui.QTreeWidgetItem(item_3)
        self.treeWidget.topLevelItem(1).child(2).child(4).child(0).child(0).setText(0, QtGui.QApplication.translate("MainWindow", "FTDI 2232H", None, QtGui.QApplication.UnicodeUTF8))
        item_4.setIcon(0, icon15)
        item_3 = QtGui.QTreeWidgetItem(item_2)
        self.treeWidget.topLevelItem(1).child(2).child(4).child(1).setText(0, QtGui.QApplication.translate("MainWindow", "Parallel", None, QtGui.QApplication.UnicodeUTF8))
        item_3 = QtGui.QTreeWidgetItem(item_2)
        self.treeWidget.topLevelItem(1).child(2).child(4).child(2).setText(0, QtGui.QApplication.translate("MainWindow", "JTAG", None, QtGui.QApplication.UnicodeUTF8))
        item_2 = QtGui.QTreeWidgetItem(item_1)
        self.treeWidget.topLevelItem(1).child(2).child(5).setText(0, QtGui.QApplication.translate("MainWindow", "Position", None, QtGui.QApplication.UnicodeUTF8))
        item_3 = QtGui.QTreeWidgetItem(item_2)
        self.treeWidget.topLevelItem(1).child(2).child(5).child(0).setText(0, QtGui.QApplication.translate("MainWindow", "Newport ESP300", None, QtGui.QApplication.UnicodeUTF8))
        item_3.setIcon(0, icon16)
        item_1 = QtGui.QTreeWidgetItem(item_0)
        self.treeWidget.topLevelItem(1).child(3).setText(0, QtGui.QApplication.translate("MainWindow", "Generic measurements", None, QtGui.QApplication.UnicodeUTF8))
        item_2 = QtGui.QTreeWidgetItem(item_1)
        self.treeWidget.topLevelItem(1).child(3).child(0).setText(0, QtGui.QApplication.translate("MainWindow", "Voltage", None, QtGui.QApplication.UnicodeUTF8))
        item_3 = QtGui.QTreeWidgetItem(item_2)
        self.treeWidget.topLevelItem(1).child(3).child(0).child(0).setText(0, QtGui.QApplication.translate("MainWindow", "Average voltage", None, QtGui.QApplication.UnicodeUTF8))
        item_4 = QtGui.QTreeWidgetItem(item_3)
        self.treeWidget.topLevelItem(1).child(3).child(0).child(0).child(0).setText(0, QtGui.QApplication.translate("MainWindow", "Agilent L4411A", None, QtGui.QApplication.UnicodeUTF8))
        item_4.setIcon(0, icon7)
        item_4 = QtGui.QTreeWidgetItem(item_3)
        self.treeWidget.topLevelItem(1).child(3).child(0).child(0).child(1).setText(0, QtGui.QApplication.translate("MainWindow", "Agilent DSO6014L", None, QtGui.QApplication.UnicodeUTF8))
        item_4.setIcon(0, icon9)
        item_3 = QtGui.QTreeWidgetItem(item_2)
        self.treeWidget.topLevelItem(1).child(3).child(0).child(1).setText(0, QtGui.QApplication.translate("MainWindow", "Time-domain voltage", None, QtGui.QApplication.UnicodeUTF8))
        item_4 = QtGui.QTreeWidgetItem(item_3)
        self.treeWidget.topLevelItem(1).child(3).child(0).child(1).child(0).setText(0, QtGui.QApplication.translate("MainWindow", "Agilent DSO6014A", None, QtGui.QApplication.UnicodeUTF8))
        item_4.setIcon(0, icon9)
        item_4 = QtGui.QTreeWidgetItem(item_3)
        self.treeWidget.topLevelItem(1).child(3).child(0).child(1).child(1).setText(0, QtGui.QApplication.translate("MainWindow", "NI PCI-6251", None, QtGui.QApplication.UnicodeUTF8))
        item_4.setIcon(0, icon11)
        item_2 = QtGui.QTreeWidgetItem(item_1)
        self.treeWidget.topLevelItem(1).child(3).child(1).setText(0, QtGui.QApplication.translate("MainWindow", "Current", None, QtGui.QApplication.UnicodeUTF8))
        item_3 = QtGui.QTreeWidgetItem(item_2)
        self.treeWidget.topLevelItem(1).child(3).child(1).child(0).setText(0, QtGui.QApplication.translate("MainWindow", "Average current", None, QtGui.QApplication.UnicodeUTF8))
        item_4 = QtGui.QTreeWidgetItem(item_3)
        self.treeWidget.topLevelItem(1).child(3).child(1).child(0).child(0).setText(0, QtGui.QApplication.translate("MainWindow", "Shunt current measurement", None, QtGui.QApplication.UnicodeUTF8))
        item_4.setIcon(0, icon8)
        item_4 = QtGui.QTreeWidgetItem(item_3)
        self.treeWidget.topLevelItem(1).child(3).child(1).child(0).child(1).setText(0, QtGui.QApplication.translate("MainWindow", "Agilent L4411A", None, QtGui.QApplication.UnicodeUTF8))
        item_4.setIcon(0, icon7)
        item_2 = QtGui.QTreeWidgetItem(item_1)
        self.treeWidget.topLevelItem(1).child(3).child(2).setText(0, QtGui.QApplication.translate("MainWindow", "Resistance", None, QtGui.QApplication.UnicodeUTF8))
        item_3 = QtGui.QTreeWidgetItem(item_2)
        self.treeWidget.topLevelItem(1).child(3).child(2).child(0).setText(0, QtGui.QApplication.translate("MainWindow", "Agilent L4411A", None, QtGui.QApplication.UnicodeUTF8))
        item_3.setIcon(0, icon7)
        item_2 = QtGui.QTreeWidgetItem(item_1)
        self.treeWidget.topLevelItem(1).child(3).child(3).setText(0, QtGui.QApplication.translate("MainWindow", "Power", None, QtGui.QApplication.UnicodeUTF8))
        item_3 = QtGui.QTreeWidgetItem(item_2)
        self.treeWidget.topLevelItem(1).child(3).child(3).child(0).setText(0, QtGui.QApplication.translate("MainWindow", "Transmitted power", None, QtGui.QApplication.UnicodeUTF8))
        item_3.setIcon(0, icon8)
        item_3 = QtGui.QTreeWidgetItem(item_2)
        self.treeWidget.topLevelItem(1).child(3).child(3).child(1).setText(0, QtGui.QApplication.translate("MainWindow", "Agilent N9010A", None, QtGui.QApplication.UnicodeUTF8))
        item_3.setIcon(0, icon12)
        item_3 = QtGui.QTreeWidgetItem(item_2)
        self.treeWidget.topLevelItem(1).child(3).child(3).child(2).setText(0, QtGui.QApplication.translate("MainWindow", "Agilent E4419B", None, QtGui.QApplication.UnicodeUTF8))
        item_3.setIcon(0, icon10)
        item_2 = QtGui.QTreeWidgetItem(item_1)
        self.treeWidget.topLevelItem(1).child(3).child(4).setText(0, QtGui.QApplication.translate("MainWindow", "Frequency", None, QtGui.QApplication.UnicodeUTF8))
        item_3 = QtGui.QTreeWidgetItem(item_2)
        self.treeWidget.topLevelItem(1).child(3).child(4).child(0).setText(0, QtGui.QApplication.translate("MainWindow", "Agilent 53220A", None, QtGui.QApplication.UnicodeUTF8))
        item_3.setIcon(0, icon11)
        item_3 = QtGui.QTreeWidgetItem(item_2)
        self.treeWidget.topLevelItem(1).child(3).child(4).child(1).setText(0, QtGui.QApplication.translate("MainWindow", "Agilent DSO6014L", None, QtGui.QApplication.UnicodeUTF8))
        item_3.setIcon(0, icon9)
        item_2 = QtGui.QTreeWidgetItem(item_1)
        self.treeWidget.topLevelItem(1).child(3).child(5).setText(0, QtGui.QApplication.translate("MainWindow", "Transfer parameters", None, QtGui.QApplication.UnicodeUTF8))
        item_3 = QtGui.QTreeWidgetItem(item_2)
        self.treeWidget.topLevelItem(1).child(3).child(5).child(0).setText(0, QtGui.QApplication.translate("MainWindow", "S-parameters", None, QtGui.QApplication.UnicodeUTF8))
        item_4 = QtGui.QTreeWidgetItem(item_3)
        self.treeWidget.topLevelItem(1).child(3).child(5).child(0).child(0).setText(0, QtGui.QApplication.translate("MainWindow", "HP 8720C", None, QtGui.QApplication.UnicodeUTF8))
        item_4.setIcon(0, icon11)
        item_3 = QtGui.QTreeWidgetItem(item_2)
        self.treeWidget.topLevelItem(1).child(3).child(5).child(1).setText(0, QtGui.QApplication.translate("MainWindow", "Z-parameters", None, QtGui.QApplication.UnicodeUTF8))
        item_4 = QtGui.QTreeWidgetItem(item_3)
        self.treeWidget.topLevelItem(1).child(3).child(5).child(1).child(0).setText(0, QtGui.QApplication.translate("MainWindow", "S to Z", None, QtGui.QApplication.UnicodeUTF8))
        item_4.setIcon(0, icon8)
        item_4 = QtGui.QTreeWidgetItem(item_3)
        self.treeWidget.topLevelItem(1).child(3).child(5).child(1).child(1).setText(0, QtGui.QApplication.translate("MainWindow", "HP 8720C", None, QtGui.QApplication.UnicodeUTF8))
        item_4.setIcon(0, icon11)
        item_3 = QtGui.QTreeWidgetItem(item_2)
        self.treeWidget.topLevelItem(1).child(3).child(5).child(2).setText(0, QtGui.QApplication.translate("MainWindow", "X-parameters", None, QtGui.QApplication.UnicodeUTF8))
        item_4 = QtGui.QTreeWidgetItem(item_3)
        self.treeWidget.topLevelItem(1).child(3).child(5).child(2).child(0).setText(0, QtGui.QApplication.translate("MainWindow", "X11 from spectrum", None, QtGui.QApplication.UnicodeUTF8))
        item_4.setIcon(0, icon8)
        item_4 = QtGui.QTreeWidgetItem(item_3)
        self.treeWidget.topLevelItem(1).child(3).child(5).child(2).child(1).setText(0, QtGui.QApplication.translate("MainWindow", "Agilent N5247A", None, QtGui.QApplication.UnicodeUTF8))
        item_4.setIcon(0, icon11)
        item_3 = QtGui.QTreeWidgetItem(item_2)
        self.treeWidget.topLevelItem(1).child(3).child(5).child(3).setText(0, QtGui.QApplication.translate("MainWindow", "Time-domain", None, QtGui.QApplication.UnicodeUTF8))
        item_4 = QtGui.QTreeWidgetItem(item_3)
        self.treeWidget.topLevelItem(1).child(3).child(5).child(3).child(0).setText(0, QtGui.QApplication.translate("MainWindow", "Agilent 86100A/54754A", None, QtGui.QApplication.UnicodeUTF8))
        item_4.setIcon(0, icon9)
        item_2 = QtGui.QTreeWidgetItem(item_1)
        self.treeWidget.topLevelItem(1).child(3).child(6).setText(0, QtGui.QApplication.translate("MainWindow", "Data integrity", None, QtGui.QApplication.UnicodeUTF8))
        item_2 = QtGui.QTreeWidgetItem(item_1)
        self.treeWidget.topLevelItem(1).child(3).child(7).setText(0, QtGui.QApplication.translate("MainWindow", "Signal integrity", None, QtGui.QApplication.UnicodeUTF8))
        item_3 = QtGui.QTreeWidgetItem(item_2)
        self.treeWidget.topLevelItem(1).child(3).child(7).child(0).setText(0, QtGui.QApplication.translate("MainWindow", "BER", None, QtGui.QApplication.UnicodeUTF8))
        item_3 = QtGui.QTreeWidgetItem(item_2)
        self.treeWidget.topLevelItem(1).child(3).child(7).child(1).setText(0, QtGui.QApplication.translate("MainWindow", "Jitter", None, QtGui.QApplication.UnicodeUTF8))
        item_1 = QtGui.QTreeWidgetItem(item_0)
        self.treeWidget.topLevelItem(1).child(4).setText(0, QtGui.QApplication.translate("MainWindow", "Control", None, QtGui.QApplication.UnicodeUTF8))
        item_2 = QtGui.QTreeWidgetItem(item_1)
        self.treeWidget.topLevelItem(1).child(4).child(0).setText(0, QtGui.QApplication.translate("MainWindow", "Sweep", None, QtGui.QApplication.UnicodeUTF8))
        item_2.setIcon(0, icon8)
        item_2 = QtGui.QTreeWidgetItem(item_1)
        self.treeWidget.topLevelItem(1).child(4).child(1).setText(0, QtGui.QApplication.translate("MainWindow", "Piecewise", None, QtGui.QApplication.UnicodeUTF8))
        item_2.setIcon(0, icon8)
        item_2 = QtGui.QTreeWidgetItem(item_1)
        self.treeWidget.topLevelItem(1).child(4).child(2).setText(0, QtGui.QApplication.translate("MainWindow", "Criterion", None, QtGui.QApplication.UnicodeUTF8))
        item_2.setIcon(0, icon8)
        self.treeWidget.header().setVisible(False)
        self.gridLayout_3.addWidget(self.treeWidget, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab_2, _fromUtf8(""))
        self.horizontalLayout_3.addWidget(self.tabWidget)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1024, 23))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("MS Shell Dlg 2"))
        font.setPointSize(10)
        self.menubar.setFont(font)
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setTitle(QtGui.QApplication.translate("MainWindow", "File", None, QtGui.QApplication.UnicodeUTF8))
        self.menuFile.setObjectName(_fromUtf8("menuFile"))
        self.menuEdit = QtGui.QMenu(self.menubar)
        self.menuEdit.setTitle(QtGui.QApplication.translate("MainWindow", "Edit", None, QtGui.QApplication.UnicodeUTF8))
        self.menuEdit.setObjectName(_fromUtf8("menuEdit"))
        self.menuView = QtGui.QMenu(self.menubar)
        self.menuView.setTitle(QtGui.QApplication.translate("MainWindow", "View", None, QtGui.QApplication.UnicodeUTF8))
        self.menuView.setObjectName(_fromUtf8("menuView"))
        self.menuLogging_level = QtGui.QMenu(self.menuView)
        self.menuLogging_level.setTitle(QtGui.QApplication.translate("MainWindow", "Logging level", None, QtGui.QApplication.UnicodeUTF8))
        self.menuLogging_level.setObjectName(_fromUtf8("menuLogging_level"))
        self.menuHelp = QtGui.QMenu(self.menubar)
        self.menuHelp.setTitle(QtGui.QApplication.translate("MainWindow", "Help", None, QtGui.QApplication.UnicodeUTF8))
        self.menuHelp.setObjectName(_fromUtf8("menuHelp"))
        MainWindow.setMenuBar(self.menubar)
        self.resultViewer = QtGui.QDockWidget(MainWindow)
        self.resultViewer.setFeatures(QtGui.QDockWidget.DockWidgetMovable)
        self.resultViewer.setAllowedAreas(QtCore.Qt.BottomDockWidgetArea)
        self.resultViewer.setWindowTitle(QtGui.QApplication.translate("MainWindow", "Result Viewer", None, QtGui.QApplication.UnicodeUTF8))
        self.resultViewer.setObjectName(_fromUtf8("resultViewer"))
        self.dockWidgetContents_5 = QtGui.QWidget()
        self.dockWidgetContents_5.setObjectName(_fromUtf8("dockWidgetContents_5"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.dockWidgetContents_5)
        self.horizontalLayout.setMargin(0)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.mplwidget = MatplotlibWidget(self.dockWidgetContents_5)
        self.mplwidget.setObjectName(_fromUtf8("mplwidget"))
        self.horizontalLayout.addWidget(self.mplwidget)
        self.resultViewer.setWidget(self.dockWidgetContents_5)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(8), self.resultViewer)
        self.experimentViewer = QtGui.QDockWidget(MainWindow)
        self.experimentViewer.setFeatures(QtGui.QDockWidget.DockWidgetMovable)
        self.experimentViewer.setAllowedAreas(QtCore.Qt.BottomDockWidgetArea)
        self.experimentViewer.setWindowTitle(QtGui.QApplication.translate("MainWindow", "Experiment Viewer", None, QtGui.QApplication.UnicodeUTF8))
        self.experimentViewer.setObjectName(_fromUtf8("experimentViewer"))
        self.dockWidgetContents_6 = QtGui.QWidget()
        self.dockWidgetContents_6.setObjectName(_fromUtf8("dockWidgetContents_6"))
        self.gridLayout_4 = QtGui.QGridLayout(self.dockWidgetContents_6)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.doubleSpinBox = QtGui.QDoubleSpinBox(self.dockWidgetContents_6)
        self.doubleSpinBox.setObjectName(_fromUtf8("doubleSpinBox"))
        self.gridLayout_4.addWidget(self.doubleSpinBox, 0, 0, 1, 1)
        self.doubleSpinBox_2 = QtGui.QDoubleSpinBox(self.dockWidgetContents_6)
        self.doubleSpinBox_2.setObjectName(_fromUtf8("doubleSpinBox_2"))
        self.gridLayout_4.addWidget(self.doubleSpinBox_2, 1, 0, 1, 1)
        self.experimentViewer.setWidget(self.dockWidgetContents_6)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(8), self.experimentViewer)
        self.subExperiment = QtGui.QDockWidget(MainWindow)
        self.subExperiment.setFeatures(QtGui.QDockWidget.DockWidgetClosable|QtGui.QDockWidget.DockWidgetMovable)
        self.subExperiment.setAllowedAreas(QtCore.Qt.RightDockWidgetArea)
        self.subExperiment.setWindowTitle(QtGui.QApplication.translate("MainWindow", "Sub-experiment", None, QtGui.QApplication.UnicodeUTF8))
        self.subExperiment.setObjectName(_fromUtf8("subExperiment"))
        self.dockWidgetContents_7 = QtGui.QWidget()
        self.dockWidgetContents_7.setObjectName(_fromUtf8("dockWidgetContents_7"))
        self.gridLayout_5 = QtGui.QGridLayout(self.dockWidgetContents_7)
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.horizontalSlider = QtGui.QSlider(self.dockWidgetContents_7)
        self.horizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider.setObjectName(_fromUtf8("horizontalSlider"))
        self.gridLayout_5.addWidget(self.horizontalSlider, 0, 0, 1, 1)
        self.subExperiment.setWidget(self.dockWidgetContents_7)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(2), self.subExperiment)
        self.logWindow = QtGui.QDockWidget(MainWindow)
        self.logWindow.setFeatures(QtGui.QDockWidget.DockWidgetMovable)
        self.logWindow.setAllowedAreas(QtCore.Qt.BottomDockWidgetArea|QtCore.Qt.RightDockWidgetArea)
        self.logWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "Log", None, QtGui.QApplication.UnicodeUTF8))
        self.logWindow.setObjectName(_fromUtf8("logWindow"))
        self.dockWidgetContents_8 = QtGui.QWidget()
        self.dockWidgetContents_8.setObjectName(_fromUtf8("dockWidgetContents_8"))
        self.gridLayout_6 = QtGui.QGridLayout(self.dockWidgetContents_8)
        self.gridLayout_6.setMargin(0)
        self.gridLayout_6.setObjectName(_fromUtf8("gridLayout_6"))
        self.listView = QtGui.QListView(self.dockWidgetContents_8)
        self.listView.setObjectName(_fromUtf8("listView"))
        self.gridLayout_6.addWidget(self.listView, 0, 0, 1, 1)
        self.logWindow.setWidget(self.dockWidgetContents_8)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(8), self.logWindow)
        self.metadataViewer = QtGui.QDockWidget(MainWindow)
        self.metadataViewer.setFeatures(QtGui.QDockWidget.DockWidgetClosable|QtGui.QDockWidget.DockWidgetMovable)
        self.metadataViewer.setWindowTitle(QtGui.QApplication.translate("MainWindow", "Metadata", None, QtGui.QApplication.UnicodeUTF8))
        self.metadataViewer.setObjectName(_fromUtf8("metadataViewer"))
        self.dockWidgetContents = QtGui.QWidget()
        self.dockWidgetContents.setObjectName(_fromUtf8("dockWidgetContents"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout(self.dockWidgetContents)
        self.horizontalLayout_4.setMargin(0)
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.scrollArea = QtGui.QScrollArea(self.dockWidgetContents)
        self.scrollArea.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName(_fromUtf8("scrollArea"))
        self.scrollAreaWidgetContents = QtGui.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 318, 307))
        self.scrollAreaWidgetContents.setObjectName(_fromUtf8("scrollAreaWidgetContents"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.scrollAreaWidgetContents)
        self.horizontalLayout_2.setMargin(0)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setSpacing(3)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.label = QtGui.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setText(QtGui.QApplication.translate("MainWindow", "Name*:", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout.addWidget(self.label, 0, 0, 1, 2)
        self.lineEdit = QtGui.QLineEdit(self.scrollAreaWidgetContents)
        self.lineEdit.setText(QtGui.QApplication.translate("MainWindow", "x-DPI 1", None, QtGui.QApplication.UnicodeUTF8))
        self.lineEdit.setObjectName(_fromUtf8("lineEdit"))
        self.gridLayout.addWidget(self.lineEdit, 0, 2, 1, 1)
        self.label_2 = QtGui.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setText(QtGui.QApplication.translate("MainWindow", "DUT*:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 2)
        self.lineEdit_2 = QtGui.QLineEdit(self.scrollAreaWidgetContents)
        self.lineEdit_2.setText(QtGui.QApplication.translate("MainWindow", "LM7805", None, QtGui.QApplication.UnicodeUTF8))
        self.lineEdit_2.setObjectName(_fromUtf8("lineEdit_2"))
        self.gridLayout.addWidget(self.lineEdit_2, 1, 2, 1, 1)
        self.label_3 = QtGui.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setText(QtGui.QApplication.translate("MainWindow", "Operator*:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout.addWidget(self.label_3, 2, 0, 1, 2)
        self.lineEdit_3 = QtGui.QLineEdit(self.scrollAreaWidgetContents)
        self.lineEdit_3.setText(QtGui.QApplication.translate("MainWindow", "Sjoerd", None, QtGui.QApplication.UnicodeUTF8))
        self.lineEdit_3.setObjectName(_fromUtf8("lineEdit_3"))
        self.gridLayout.addWidget(self.lineEdit_3, 2, 2, 1, 1)
        self.label_4 = QtGui.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setText(QtGui.QApplication.translate("MainWindow", "Start*:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout.addWidget(self.label_4, 3, 0, 1, 2)
        self.lineEdit_4 = QtGui.QLineEdit(self.scrollAreaWidgetContents)
        self.lineEdit_4.setText(QtGui.QApplication.translate("MainWindow", "16-04-2012 14:05:21", None, QtGui.QApplication.UnicodeUTF8))
        self.lineEdit_4.setReadOnly(True)
        self.lineEdit_4.setObjectName(_fromUtf8("lineEdit_4"))
        self.gridLayout.addWidget(self.lineEdit_4, 3, 2, 1, 1)
        self.label_5 = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.label_5.setText(QtGui.QApplication.translate("MainWindow", "Calibration kit:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.gridLayout.addWidget(self.label_5, 4, 0, 1, 2)
        self.lineEdit_5 = QtGui.QLineEdit(self.scrollAreaWidgetContents)
        self.lineEdit_5.setText(QtGui.QApplication.translate("MainWindow", "1-Sjoerd", None, QtGui.QApplication.UnicodeUTF8))
        self.lineEdit_5.setObjectName(_fromUtf8("lineEdit_5"))
        self.gridLayout.addWidget(self.lineEdit_5, 4, 2, 1, 1)
        self.pushButton_4 = QtGui.QPushButton(self.scrollAreaWidgetContents)
        self.pushButton_4.setText(_fromUtf8(""))
        self.pushButton_4.setIcon(icon6)
        self.pushButton_4.setIconSize(QtCore.QSize(16, 16))
        self.pushButton_4.setFlat(True)
        self.pushButton_4.setObjectName(_fromUtf8("pushButton_4"))
        self.gridLayout.addWidget(self.pushButton_4, 4, 3, 1, 1)
        self.label_6 = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.label_6.setText(QtGui.QApplication.translate("MainWindow", "Instance number*:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.gridLayout.addWidget(self.label_6, 5, 0, 1, 2)
        self.spinBox = QtGui.QSpinBox(self.scrollAreaWidgetContents)
        self.spinBox.setProperty("value", 1)
        self.spinBox.setObjectName(_fromUtf8("spinBox"))
        self.gridLayout.addWidget(self.spinBox, 5, 2, 1, 1)
        self.pushButton_5 = QtGui.QPushButton(self.scrollAreaWidgetContents)
        self.pushButton_5.setText(_fromUtf8(""))
        self.pushButton_5.setIcon(icon6)
        self.pushButton_5.setIconSize(QtCore.QSize(16, 16))
        self.pushButton_5.setFlat(True)
        self.pushButton_5.setObjectName(_fromUtf8("pushButton_5"))
        self.gridLayout.addWidget(self.pushButton_5, 5, 3, 1, 1)
        self.comboBox = QtGui.QComboBox(self.scrollAreaWidgetContents)
        self.comboBox.setObjectName(_fromUtf8("comboBox"))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.setItemText(0, QtGui.QApplication.translate("MainWindow", "Text", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.setItemText(1, QtGui.QApplication.translate("MainWindow", "Number", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.setItemText(2, QtGui.QApplication.translate("MainWindow", "Float", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.setItemText(3, QtGui.QApplication.translate("MainWindow", "Boolean", None, QtGui.QApplication.UnicodeUTF8))
        self.gridLayout.addWidget(self.comboBox, 6, 2, 1, 1)
        self.pushButton_6 = QtGui.QPushButton(self.scrollAreaWidgetContents)
        self.pushButton_6.setText(_fromUtf8(""))
        icon20 = QtGui.QIcon()
        icon20.addPixmap(QtGui.QPixmap(_fromUtf8(":/results/Add.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_6.setIcon(icon20)
        self.pushButton_6.setIconSize(QtCore.QSize(16, 16))
        self.pushButton_6.setFlat(True)
        self.pushButton_6.setObjectName(_fromUtf8("pushButton_6"))
        self.gridLayout.addWidget(self.pushButton_6, 6, 3, 1, 1)
        spacerItem1 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem1, 9, 0, 1, 4)
        self.lineEdit_8 = QtGui.QLineEdit(self.scrollAreaWidgetContents)
        self.lineEdit_8.setText(_fromUtf8(""))
        self.lineEdit_8.setPlaceholderText(QtGui.QApplication.translate("MainWindow", "Field name", None, QtGui.QApplication.UnicodeUTF8))
        self.lineEdit_8.setObjectName(_fromUtf8("lineEdit_8"))
        self.gridLayout.addWidget(self.lineEdit_8, 6, 0, 1, 1)
        self.checkBox = QtGui.QCheckBox(self.scrollAreaWidgetContents)
        self.checkBox.setToolTip(_fromUtf8(""))
        self.checkBox.setText(_fromUtf8(""))
        self.checkBox.setChecked(True)
        self.checkBox.setObjectName(_fromUtf8("checkBox"))
        self.gridLayout.addWidget(self.checkBox, 6, 1, 1, 1)
        self.horizontalLayout_2.addLayout(self.gridLayout)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.horizontalLayout_4.addWidget(self.scrollArea)
        self.metadataViewer.setWidget(self.dockWidgetContents)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(2), self.metadataViewer)
        self.actionSave_as_template = QtGui.QAction(MainWindow)
        self.actionSave_as_template.setText(QtGui.QApplication.translate("MainWindow", "Save as template", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSave_as_template.setObjectName(_fromUtf8("actionSave_as_template"))
        self.actionQuit = QtGui.QAction(MainWindow)
        self.actionQuit.setText(QtGui.QApplication.translate("MainWindow", "Quit", None, QtGui.QApplication.UnicodeUTF8))
        self.actionQuit.setObjectName(_fromUtf8("actionQuit"))
        self.actionCopy = QtGui.QAction(MainWindow)
        self.actionCopy.setText(QtGui.QApplication.translate("MainWindow", "Copy", None, QtGui.QApplication.UnicodeUTF8))
        self.actionCopy.setObjectName(_fromUtf8("actionCopy"))
        self.actionPaste = QtGui.QAction(MainWindow)
        self.actionPaste.setText(QtGui.QApplication.translate("MainWindow", "Paste", None, QtGui.QApplication.UnicodeUTF8))
        self.actionPaste.setObjectName(_fromUtf8("actionPaste"))
        self.actionSelect_All = QtGui.QAction(MainWindow)
        self.actionSelect_All.setText(QtGui.QApplication.translate("MainWindow", "Select All", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSelect_All.setObjectName(_fromUtf8("actionSelect_All"))
        self.actionCut = QtGui.QAction(MainWindow)
        self.actionCut.setText(QtGui.QApplication.translate("MainWindow", "Cut", None, QtGui.QApplication.UnicodeUTF8))
        self.actionCut.setObjectName(_fromUtf8("actionCut"))
        self.actionErrors_only = QtGui.QAction(MainWindow)
        self.actionErrors_only.setCheckable(True)
        self.actionErrors_only.setChecked(True)
        self.actionErrors_only.setText(QtGui.QApplication.translate("MainWindow", "Errors only", None, QtGui.QApplication.UnicodeUTF8))
        self.actionErrors_only.setObjectName(_fromUtf8("actionErrors_only"))
        self.actionInfo = QtGui.QAction(MainWindow)
        self.actionInfo.setCheckable(True)
        self.actionInfo.setChecked(True)
        self.actionInfo.setText(QtGui.QApplication.translate("MainWindow", "Info", None, QtGui.QApplication.UnicodeUTF8))
        self.actionInfo.setObjectName(_fromUtf8("actionInfo"))
        self.actionDebug = QtGui.QAction(MainWindow)
        self.actionDebug.setCheckable(True)
        self.actionDebug.setChecked(True)
        self.actionDebug.setText(QtGui.QApplication.translate("MainWindow", "Debug", None, QtGui.QApplication.UnicodeUTF8))
        self.actionDebug.setObjectName(_fromUtf8("actionDebug"))
        self.actionTree_Left = QtGui.QAction(MainWindow)
        self.actionTree_Left.setText(QtGui.QApplication.translate("MainWindow", "Tree Left", None, QtGui.QApplication.UnicodeUTF8))
        self.actionTree_Left.setObjectName(_fromUtf8("actionTree_Left"))
        self.actionTree_on_Top = QtGui.QAction(MainWindow)
        self.actionTree_on_Top.setText(QtGui.QApplication.translate("MainWindow", "Tree on Top", None, QtGui.QApplication.UnicodeUTF8))
        self.actionTree_on_Top.setObjectName(_fromUtf8("actionTree_on_Top"))
        self.actionAbout = QtGui.QAction(MainWindow)
        self.actionAbout.setText(QtGui.QApplication.translate("MainWindow", "About...", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAbout.setObjectName(_fromUtf8("actionAbout"))
        self.menuFile.addAction(self.actionSave_as_template)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionQuit)
        self.menuEdit.addAction(self.actionCut)
        self.menuEdit.addAction(self.actionCopy)
        self.menuEdit.addAction(self.actionPaste)
        self.menuEdit.addAction(self.actionSelect_All)
        self.menuLogging_level.addAction(self.actionErrors_only)
        self.menuLogging_level.addAction(self.actionInfo)
        self.menuLogging_level.addAction(self.actionDebug)
        self.menuView.addAction(self.actionTree_Left)
        self.menuView.addAction(self.actionTree_on_Top)
        self.menuView.addSeparator()
        self.menuView.addAction(self.menuLogging_level.menuAction())
        self.menuHelp.addAction(self.actionAbout)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuEdit.menuAction())
        self.menubar.addAction(self.menuView.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        __sortingEnabled = self.treeWidget_2.isSortingEnabled()
        self.treeWidget_2.setSortingEnabled(False)
        self.treeWidget_2.setSortingEnabled(__sortingEnabled)
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), QtGui.QApplication.translate("MainWindow", "Results", None, QtGui.QApplication.UnicodeUTF8))
        __sortingEnabled = self.treeWidget.isSortingEnabled()
        self.treeWidget.setSortingEnabled(False)
        self.treeWidget.setSortingEnabled(__sortingEnabled)
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), QtGui.QApplication.translate("MainWindow", "Experiments", None, QtGui.QApplication.UnicodeUTF8))

from matplotlibwidget import MatplotlibWidget
import icons_rc
