# -*- coding: utf-8 -*-
"""
Manual port of scanControlDataTypes.h

@author: Sjoerd Op 't Land
"""
ERROR_OK                                            =0
ERROR_SERIAL_COMM                                   =1
ERROR_SERIAL_LLT                                    =7
ERROR_CONNECTIONLOST                                =10
ERROR_STOPSAVING                                    =100

#y the type for the RS422-multiplexer
RS422_INTERFACE_FUNCTION_AUTO                       =0
RS422_INTERFACE_FUNCTION_SERIALPORT_115200          =1
RS422_INTERFACE_FUNCTION_TRIGGER                    =2
RS422_INTERFACE_FUNCTION_CMM_TRIGGER                =3
RS422_INTERFACE_FUNCTION_ENCODER                    =4
RS422_INTERFACE_FUNCTION_DIGITAL_OUTPUT             =6
RS422_INTERFACE_FUNCTION_TRIGGER_LASER_PULSE        =7
RS422_INTERFACE_FUNCTION_SERIALPORT_57600           =8
RS422_INTERFACE_FUNCTION_SERIALPORT_38400           =9
RS422_INTERFACE_FUNCTION_SERIALPORT_19200           =10
RS422_INTERFACE_FUNCTION_SERIALPORT_9600            =11

#-Values for the is-functions
IS_FUNC_NO                                          =0
IS_FUNC_YES                                         =1

#l return-values for all functions
GENERAL_FUNCTION_DEVICE_NAME_NOT_SUPPORTED          =4
GENERAL_FUNCTION_PACKET_SIZE_CHANGED                =3
GENERAL_FUNCTION_CONTAINER_MODE_HEIGHT_CHANGED      =2
GENERAL_FUNCTION_OK                                 =1
GENERAL_FUNCTION_NOT_AVAILABLE                      =0

ERROR_GENERAL_WHILE_LOAD_PROFILE                    =-1000
ERROR_GENERAL_NOT_CONNECTED                         =-1001
ERROR_GENERAL_DEVICE_BUSY                           =-1002
ERROR_GENERAL_WHILE_LOAD_PROFILE_OR_GET_PROFILES    =-1003
ERROR_GENERAL_WHILE_GET_PROFILES                    =-1004
ERROR_GENERAL_GET_SET_ADDRESS                       =-1005
ERROR_GENERAL_POINTER_MISSING                       =-1006
ERROR_GENERAL_WHILE_SAVE_PROFILES                   =-1007
ERROR_GENERAL_SECOND_CONNECTION_TO_LLT              =-1008

#-Values for GetDeviceName
ERROR_GETDEVICENAME_SIZE_TOO_LOW                    =-1
ERROR_GETDEVICENAME_NO_BUFFER                       =-2

#-Values for Load/SaveProfiles
ERROR_LOADSAVE_WRITING_LAST_BUFFER                  =-50
ERROR_LOADSAVE_WHILE_SAVE_PROFILE                   =-51
ERROR_LOADSAVE_NO_PROFILELENGTH_POINTER             =-52
ERROR_LOADSAVE_NO_LOAD_PROFILE                      =-53
ERROR_LOADSAVE_STOP_ALREADY_LOAD                    =-54
ERROR_LOADSAVE_CANT_OPEN_FILE                       =-55
ERROR_LOADSAVE_INVALID_FILE_HEADER                  =-56
ERROR_LOADSAVE_FILE_POSITION_TOO_HIGH               =-57
ERROR_LOADSAVE_AVI_NOT_SUPPORTED                    =-58
ERROR_LOADSAVE_NO_REARRANGEMENT_POINTER             =-59
ERROR_LOADSAVE_WRONG_PROFILE_CONFIG                 =-60
ERROR_LOADSAVE_NOT_TRANSFERING                      =-61

#-Values for profile transfer functions
ERROR_PROFTRANS_SHOTS_NOT_ACTIVE                    =-100
ERROR_PROFTRANS_SHOTS_COUNT_TOO_HIGH                =-101
ERROR_PROFTRANS_WRONG_PROFILE_CONFIG                =-102
ERROR_PROFTRANS_FILE_EOF                            =-103
ERROR_PROFTRANS_NO_NEW_PROFILE                      =-104
ERROR_PROFTRANS_BUFFER_SIZE_TOO_LOW                 =-105
ERROR_PROFTRANS_NO_PROFILE_TRANSFER                 =-106
ERROR_PROFTRANS_PACKET_SIZE_TOO_HIGH                =-107
ERROR_PROFTRANS_CREATE_BUFFERS                      =-108
ERROR_PROFTRANS_WRONG_PACKET_SIZE_FOR_CONTAINER     =-109
ERROR_PROFTRANS_REFLECTION_NUMBER_TOO_HIGH          =-110
ERROR_PROFTRANS_MULTIPLE_SHOTS_ACTIV                =-111
ERROR_PROFTRANS_BUFFER_HANDOUT                      =-112
ERROR_PROFTRANS_WRONG_BUFFER_POINTER                =-113
ERROR_PROFTRANS_WRONG_TRANSFER_CONFIG               =-114

#-Values for Set/GetFunctions
ERROR_SETGETFUNCTIONS_WRONG_BUFFER_COUNT            =-150
ERROR_SETGETFUNCTIONS_PACKET_SIZE                   =-151
ERROR_SETGETFUNCTIONS_WRONG_PROFILE_CONFIG          =-152
ERROR_SETGETFUNCTIONS_NOT_SUPPORTED_RESOLUTION      =-153
ERROR_SETGETFUNCTIONS_REFLECTION_NUMBER_TOO_HIGH    =-154
ERROR_SETGETFUNCTIONS_WRONG_FEATURE_ADRESS          =-155
ERROR_SETGETFUNCTIONS_SIZE_TOO_LOW                  =-156
ERROR_SETGETFUNCTIONS_WRONG_PROFILE_SIZE            =-157
ERROR_SETGETFUNCTIONS_MOD_4                         =-158
ERROR_SETGETFUNCTIONS_REARRANGEMENT_PROFILE         =-159
ERROR_SETGETFUNCTIONS_USER_MODE_TOO_HIGH            =-160
ERROR_SETGETFUNCTIONS_USER_MODE_FACTORY_DEFAULT     =-161
ERROR_SETGETFUNCTIONS_HEARTBEAT_TOO_HIGH            =-162


#-Values PostProcessingParameter
ERROR_POSTPROCESSING_NO_PROF_BUFFER                 =-200
ERROR_POSTPROCESSING_MOD_4                          =-201
ERROR_POSTPROCESSING_NO_RESULT                      =-202
ERROR_POSTPROCESSING_LOW_BUFFERSIZE                 =-203
ERROR_POSTPROCESSING_WRONG_RESULT_SIZE              =-204

#-Values for GetDeviceInterfaces
ERROR_GETDEVINTERFACES_WIN_NOT_SUPPORTED            =-250
ERROR_GETDEVINTERFACES_REQUEST_COUNT                =-251
ERROR_GETDEVINTERFACES_CONNECTED                    =-252
ERROR_GETDEVINTERFACES_INTERNAL                     =-253

#-Values for Connect
ERROR_CONNECT_LLT_COUNT                             =-300
ERROR_CONNECT_SELECTED_LLT                          =-301
ERROR_CONNECT_ALREADY_CONNECTED                     =-302
ERROR_CONNECT_LLT_NUMBER_ALREADY_USED               =-303
ERROR_CONNECT_SERIAL_CONNECTION                     =-304
ERROR_CONNECT_INVALID_IP                            =-305

#-Values for SetPartialProfile
ERROR_PARTPROFILE_NO_PART_PROF                      =-350
ERROR_PARTPROFILE_TOO_MUCH_BYTES                    =-351
ERROR_PARTPROFILE_TOO_MUCH_POINTS                   =-352
ERROR_PARTPROFILE_NO_POINT_COUNT                    =-353
ERROR_PARTPROFILE_NOT_MOD_UNITSIZE_POINT            =-354
ERROR_PARTPROFILE_NOT_MOD_UNITSIZE_DATA             =-355

#-Values for Start/StopTransmissionAndCmmTrigger
ERROR_CMMTRIGGER_NO_DIVISOR                         =-400
ERROR_CMMTRIGGER_TIMEOUT_AFTER_TRANSFERPROFILES     =-401
ERROR_CMMTRIGGER_TIMEOUT_AFTER_SETCMMTRIGGER        =-402

#-Values for TranslateErrorValue
ERROR_TRANSERRORVALUE_WRONG_ERROR_VALUE             =-450
ERROR_TRANSERRORVALUE_BUFFER_SIZE_TOO_LOW           =-451

#rite config functions
ERROR_READWRITECONFIG_CANT_CREATE_FILE              =-500
ERROR_READWRITECONFIG_CANT_OPEN_FILE                =-501
ERROR_READWRITECONFIG_QUEUE_TO_SMALL                =-502

#on defines for the Get/SetFeature function
FEATURE_FUNCTION_SERIAL                             =0xf0000410
FEATURE_FUNCTION_LASERPOWER                         =0xf0f00824
INQUIRY_FUNCTION_LASERPOWER                         =0xf0f00524
FEATURE_FUNCTION_MEASURINGFIELD                     =0xf0f00880
INQUIRY_FUNCTION_MEASURINGFIELD                     =0xf0f00580
FEATURE_FUNCTION_TRIGGER                            =0xf0f00830
INQUIRY_FUNCTION_TRIGGER                            =0xf0f00530
FEATURE_FUNCTION_SHUTTERTIME                        =0xf0f0081c
INQUIRY_FUNCTION_SHUTTERTIME                        =0xf0f0051c
FEATURE_FUNCTION_IDLETIME                           =0xf0f00800
INQUIRY_FUNCTION_IDLETIME                           =0xf0f00500
FEATURE_FUNCTION_PROCESSING_PROFILEDATA             =0xf0f00804
INQUIRY_FUNCTION_PROCESSING_PROFILEDATA             =0xf0f00504
FEATURE_FUNCTION_THRESHOLD                          =0xf0f00810
INQUIRY_FUNCTION_THRESHOLD                          =0xf0f00510
FEATURE_FUNCTION_MAINTENANCEFUNCTIONS               =0xf0f0088c
INQUIRY_FUNCTION_MAINTENANCEFUNCTIONS               =0xf0f0058c
FEATURE_FUNCTION_ANALOGFREQUENCY                    =0xf0f00828
INQUIRY_FUNCTION_ANALOGFREQUENCY                    =0xf0f00528
FEATURE_FUNCTION_ANALOGOUTPUTMODES                  =0xf0f00820
INQUIRY_FUNCTION_ANALOGOUTPUTMODES                  =0xf0f00520
FEATURE_FUNCTION_CMMTRIGGER                         =0xf0f00888
INQUIRY_FUNCTION_CMMTRIGGER                         =0xf0f00588
FEATURE_FUNCTION_REARRANGEMENT_PROFILE              =0xf0f0080c
INQUIRY_FUNCTION_REARRANGEMENT_PROFILE              =0xf0f0050c
FEATURE_FUNCTION_PROFILE_FILTER                     =0xf0f00818
INQUIRY_FUNCTION_PROFILE_FILTER                     =0xf0f00518
FEATURE_FUNCTION_RS422_INTERFACE_FUNCTION           =0xf0f008c0
INQUIRY_FUNCTION_RS422_INTERFACE_FUNCTION           =0xf0f005c0

FEATURE_FUNCTION_SATURATION                         =0xf0f00814
INQUIRY_FUNCTION_SATURATION                         =0xf0f00514
FEATURE_FUNCTION_TEMPERATURE                        =0xf0f0082c
INQUIRY_FUNCTION_TEMPERATURE                        =0xf0f0052c
FEATURE_FUNCTION_CAPTURE_QUALITY                    =0xf0f008c4
INQUIRY_FUNCTION_CAPTURE_QUALITY                    =0xf0f005c4
FEATURE_FUNCTION_SHARPNESS                          =0xf0f00808
INQUIRY_FUNCTION_SHARPNESS                          =0xf0f00508

FEATURE_FUNCTION_PACKET_DELAY                       =0x00000d08
FEATURE_FUNCTION_CONNECTION_SPEED                   =0x00000670

#s for the return values of the ConvertProfile2Values and ConvertPartProfile2Values functions
CONVERT_WIDTH                                       =0x00000100
CONVERT_MAXIMUM                                     =0x00000200
CONVERT_THRESHOLD                                   =0x00000400
CONVERT_X                                           =0x00000800
CONVERT_Z                                           =0x00001000
CONVERT_M0                                          =0x00002000
CONVERT_M1                                          =0x00004000


#typedef enum TProfileConfig
NONE            = 0
PROFILE         = 1
CONTAINER       = 1
VIDEO_IMAGE     = 1
PURE_PROFILE    = 2
QUARTER_PROFILE = 3
CSV_PROFILE     = 4
PARTIAL_PROFILE = 5


#typedef enum TCallbackType
STD_CALL = 0
C_DECL   = 1


#typedef enum TFileType
AVI = 0
LLT = 1
CSV = 2
BMP = 3
CSV_NEG = 4


#typedef enum TTransferProfileType
NORMAL_TRANSFER = 0
SHOT_TRANSFER   = 1
NORMAL_CONTAINER_MODE = 2
SHOT_CONTAINER_MODE = 3
NONE_TRANSFER = 4


#typedef enum TTransferVideoType
VIDEO_MODE_0 = 0
VIDEO_MODE_1 = 1
NONE_VIDEOMODE = 2


#typedef enum TInterfaceType
INTF_TYPE_UNKNOWN  = 0
INTF_TYPE_SERIAL   = 1
INTF_TYPE_FIREWIRE = 2
INTF_TYPE_ETHERNET = 3